kind: pipeline
type: docker
name: Protobuf插件


clone:
  disable: true


steps:
  - name: 代码
    image: dronestock/git

  - name: 编译
    image: pangum/drone
    settings:
      output: protobuf

  - name: 发布
    image: dronestock/docker
    privileged: true
    when:
      branch:
        include:
          - master
          - dependabot/*
      event:
        - tag
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      repository: dronestock/protobuf
      username: dronestock
      password:
        from_secret: token_docker


volumes:
  - name: cache
    host:
      path: /var/lib/cache/docker
