kind: pipeline
type: docker
name: Protobuf插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: plugins/git
    pull: if-not-exists

  - name: 编译
      image: dronestock/pangu
      pull: if-not-exists
      settings:
        output: protobuf

  - name: 打包Docker并推送
    image: plugins/docker
    when:
      branch:
        - develop
        - master
    settings:
      repo: dronestock/protobuf
      tags:
        - latest
        - 0.0.1
      compress: true
      mirror: https://docker.mirrors.ustc.edu.cn
      username: dronestock
      password:
        from_secret: token_docker
