kind: secret
name: token_docker
get:
  path: secrets
  name: token_docker_dronestock
---

kind: secret
name: password_ccr
get:
  path: secrets
  name: password_ccr
---

kind: secret
name: token_github
get:
  path: secrets
  name: token_github_storezhang
---

kind: secret
name: feishu_id
get:
  path: secrets
  name: feishu_id
---

kind: secret
name: feishu_secret
get:
  path: secrets
  name: feishu_secret
---


kind: pipeline
type: docker
name: Protobuf插件


clone:
  disable: true


steps:
  - name: 取码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output:
        name: protobuf

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_ccr
    settings:
      repository: dronestock/protobuf
      tag: 0.0.$${DRONE_BUILD_NUMBER}
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true

  - name: 通知
    image: ccr.ccs.tencentyun.com/dronestock/feishu
    pull: always
    when:
      status:
        - success
        - failure
    settings:
      id:
        from_secret: feishu_id
      secret:
        from_secret: feishu_secret


volumes:
  - name: go
    host:
      path: /var/lib/cache/go
  - name: docker
    host:
      path: /var/lib/cache/docker
